### ISSUE TITLE
replace all instances of `v` with `dc`

### ISSUE THREAD

**Issue by jackparmer** [flojoy-io/nodes#29]
when we started flojoy, there was no `DataContainer` class, so as convention, we used `v` to denote "vector" for every input variable. Most of the nodes still use `v`, but we should update it to `dc` to be more precise

Eg,  all instances of
```
@flojoy
def SOME_FUNCTION(v, params):
    # bla..
```
should be 
```
@flojoy
def SOME_FUNCTION(dc, params):
    # bla..
```

**Comment by smahmed776** [comment]
@jackparmer Shouldn't it be in plural form as it is a list of `DataContainer` like `dc_inputs`?

**Comment by jackparmer** [comment]
yeah, that sounds good 👍 Envoyé de mon iPhoneLe 11 mai 2023 à 1:30 PM, Syed Mahbub ***@***.***> a écrit :﻿
@jackparmer Shouldn't it be in plural form as it is a list of DataContainer like dc_inputs?
