### ISSUE TITLE
Proper Python typing for all nodes

### ISSUE THREAD

**Issue by itsjoeoui** [flojoy-io/nodes#37]

**Comment by youngsun4786** [comment]
for files without DataContainers, it seems that DataContainer types aren't being recognized as expected. Should I still specify the types regardless or import DataContainer from flojoy?


![Image](https://github.com/flojoy-io/nodes/assets/83793112/5725f1d2-aad5-4136-821c-c3e739429d6f)


There were certain files that took in DataContainer as parameter but weren't used. Should we still leave them as they are and specify the types?



![Image](https://github.com/flojoy-io/nodes/assets/83793112/df9408f6-2397-40dd-9b38-4acb36d1f8f3)
